# Generated by Django 4.2.20 on 2025-04-29 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udalost',
            name='celodenni',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='udalost',
            name='jen_zacatek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='udalost',
            name='konec',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 10, 35, 12, 475945)),
        ),
        migrations.AddField(
            model_name='udalost',
            name='zacatek',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 10, 35, 12, 475945)),
        ),
    ]
