# Generated by Django 4.2.20 on 2025-04-30 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_udalost_celodenni_udalost_jen_zacatek_udalost_konec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udalost',
            name='konec',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 13, 35, 331946)),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='zacatek',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 13, 35, 331946)),
        ),
        migrations.CreateModel(
            name='Ukol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=150)),
                ('popis', models.TextField(max_length=500, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 13, 35, 331946))),
                ('splneno', models.BooleanField(default=False)),
                ('udalost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calen.udalost')),
            ],
        ),
    ]
